// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMLBWN7nLiOmDBZI0xIWhCgoiwVO3w1E',
    appId: '1:916073348632:web:006b5a07831c366322cd6d',
    messagingSenderId: '916073348632',
    projectId: 'pickbuzz-ad94c',
    authDomain: 'pickbuzz-ad94c.firebaseapp.com',
    databaseURL: 'https://pickbuzz-ad94c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickbuzz-ad94c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nKlqjdDgJMe8dVlD9ZJPK-uzJJweBGI',
    appId: '1:916073348632:android:7783f713ec9892df22cd6d',
    messagingSenderId: '916073348632',
    projectId: 'pickbuzz-ad94c',
    databaseURL: 'https://pickbuzz-ad94c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickbuzz-ad94c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQvIZCjorFMrahsOEQ2FZ8EPdH6veVzoA',
    appId: '1:916073348632:ios:e7e18b00b42d784122cd6d',
    messagingSenderId: '916073348632',
    projectId: 'pickbuzz-ad94c',
    databaseURL: 'https://pickbuzz-ad94c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickbuzz-ad94c.appspot.com',
    iosClientId: '916073348632-f9ujpefjcv4cccacqpspqtujtb62cmpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQvIZCjorFMrahsOEQ2FZ8EPdH6veVzoA',
    appId: '1:916073348632:ios:8c03af6ac0dac81922cd6d',
    messagingSenderId: '916073348632',
    projectId: 'pickbuzz-ad94c',
    databaseURL: 'https://pickbuzz-ad94c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pickbuzz-ad94c.appspot.com',
    iosClientId: '916073348632-prue8kl5kftppakroe86m1av05juq40m.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickbuzz.RunnerTests',
  );
}
